# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('863ddec814e46da2aa09f58d9486faeb_MTAzNDM1MjAxMi0wNi0yNCAyMjoyOTowNi45NzczMDM')
  end)
end
